blank_issues_enabled: false
contact_links:
  - name: ğŸ“š Read the Docs
    url: https://github.com/shashankatthaluri/wisprflex/tree/main/docs
    about: Most questions are answered here.

  - name: ğŸ”’ Security Issues
    url: https://github.com/shashankatthaluri/wisprflex/security
    about: Please report vulnerabilities privately.
